image: python:2.7

pipelines:
  default:
    - step:
        name: Python2.7
        script:
          - pip install -U tox
          - tox -e py27
    - step:
        name: Python3.4
        image: python:3.4
        script:
          - pip install -U tox
          - tox -e py34
    - step:
        name: Python3.5
        image: python:3.5
        script:
          - pip install -U tox
          - tox -e py35
    - step:
        name: coverage2.7
        script:
          - pip install -U tox
          - tox -e coverage
    - step:
        name: doctest
        script:
          - pip install -U tox
          - tox -e coverage
    