image: maven:3.3.9

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - apt-get update
          - apt-get install -y python2 python3 pip
          - pip install -U tox
          - tox
