image: python:2.7

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -U tox
          - tox -e py27
    - step:
        image: python:3.4
        caches:
          - pip3
        script:
          - pip3 install -U tox
          - tox -e py34,coverage

